// SPDX-License-Identifier: Apache-2.0

export const engineeringReportRuntime = String.raw`
(function(){
  'use strict';
  var runtimeIssues=[];
  var runtimeDiagnostic=document.getElementById('report-runtime-diagnostic');if(!runtimeDiagnostic&&document.body){runtimeDiagnostic=document.createElement('div');runtimeDiagnostic.id='report-runtime-diagnostic';runtimeDiagnostic.className='empty-result';runtimeDiagnostic.setAttribute('role','alert');runtimeDiagnostic.hidden=true;document.body.insertBefore(runtimeDiagnostic,document.body.firstChild);}
  function reportRuntimeIssue(surface,error){var detail=error&&error.message?error.message:String(error||'Unknown rendering failure');var message=surface+': '+detail;if(runtimeIssues.indexOf(message)>=0)return;runtimeIssues.push(message);var diagnostic=document.getElementById('report-runtime-diagnostic');if(diagnostic){diagnostic.hidden=false;diagnostic.textContent='Interactive report rendering diagnostic. '+runtimeIssues.join(' | ');}var target=surface==='Plotly field'?document.getElementById('plotly-field'):surface==='Result graph'?document.getElementById('result-chart'):null;if(target&&target.parentElement){target.parentElement.setAttribute('data-render-error','true');}if(window.console&&window.console.error)window.console.error('[SPIKE report] '+message,error);}
  function renderSafely(surface,render){try{return render();}catch(error){reportRuntimeIssue(surface,error);return null;}}
  window.addEventListener('error',function(event){reportRuntimeIssue('Report script',event.error||event.message);});
  window.addEventListener('unhandledrejection',function(event){reportRuntimeIssue('Report script',event.reason);});
  var dataNode=document.getElementById('report-data');
  var evidenceNode=document.getElementById('evidence-data');
  var data=renderSafely('Report data',function(){return JSON.parse(dataNode&&dataNode.textContent||'null');});
  var evidence=renderSafely('Report data',function(){return JSON.parse(evidenceNode&&evidenceNode.textContent||'{}');})||{};
  var canvas=document.getElementById('board-canvas');
  var context=canvas&&canvas.getContext?canvas.getContext('2d'):null;
  var graph=document.getElementById('result-chart');
  var graphContext=graph&&graph.getContext?graph.getContext('2d'):null;
  function markRenderReady(target,selector){var shell=target&&target.closest?target.closest(selector):null;if(shell)shell.setAttribute('data-render-ready','true');}
  var view='2d', zoom=1, panX=0, panY=0, yaw=-0.65, pitch=0.72, dragging=false, lastX=0, lastY=0, fieldDisplay='raw', contourHoverPoints=[];
  var boardFrame=0;function scheduleBoardDraw(){if(boardFrame)return;boardFrame=window.requestAnimationFrame?window.requestAnimationFrame(function(){boardFrame=0;drawBoard();}):setTimeout(function(){boardFrame=0;drawBoard();},16);}
  var metricSelect=document.getElementById('viewport-metric');
  var graphSelect=document.getElementById('graph-series');
  var tooltip=document.getElementById('graph-tooltip');
  var colors=['#4a8df6','#3bc9db','#4dd4ac','#d8df58','#ffb84a','#ef6158'];
  try{
  var netTabs=Array.prototype.slice.call(document.querySelectorAll('[data-net-tab]'));
  var netPanels=Array.prototype.slice.call(document.querySelectorAll('[data-net-panel]'));
  function selectNet(net){netTabs.forEach(function(tab){var active=tab.getAttribute('data-net-tab')===net;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',active?'true':'false');});netPanels.forEach(function(panel){panel.hidden=panel.getAttribute('data-net-panel')!==net;});var dataset=(data&&data.datasets||[]).find(function(item){return item.id===net;});if(dataset){data.fields=dataset.fields||{};data.impedance=dataset.impedance||[];graphView=null;renderSafely('Board canvas',drawBoard);renderSafely('Result graph',drawGraph);}}
  netTabs.forEach(function(tab){tab.addEventListener('click',function(){selectNet(tab.getAttribute('data-net-tab'));});});
  var reportNav=document.querySelector('[data-report-nav]');
  var navLinks=reportNav?Array.prototype.slice.call(reportNav.querySelectorAll('a[href^="#"]')):[];
  function navHash(link){return link&&link.getAttribute('href')||'';}
  function markCurrentNav(link){navLinks.forEach(function(item){if(item===link)item.setAttribute('aria-current','location');else item.removeAttribute('aria-current');});}
  function linkForHash(hash){return navLinks.find(function(link){return navHash(link)===hash;})||null;}
  function targetForHash(hash){if(!hash||hash.charAt(0)!=='#')return null;var id=hash.slice(1);try{id=decodeURIComponent(id);}catch(_error){}return id?document.getElementById(id):null;}
  function activateReportHash(hash,scroll){var link=linkForHash(hash),target=targetForHash(hash);if(!target)return false;var net=link&&link.getAttribute('data-nav-net')||target.getAttribute('data-net-panel');if(net)selectNet(net);if(link)markCurrentNav(link);if(scroll&&target.scrollIntoView)target.scrollIntoView({block:'start'});return true;}
  navLinks.forEach(function(link){link.addEventListener('click',function(event){var hash=navHash(link);if(!activateReportHash(hash,true))return;if(event&&event.preventDefault)event.preventDefault();if(window.history&&window.history.pushState)window.history.pushState(null,'',hash);else window.location.hash=hash;});});
  window.addEventListener('hashchange',function(){activateReportHash(window.location.hash,false);});
  if(!activateReportHash(window.location&&window.location.hash||'',false)&&netTabs.length)selectNet(netTabs[0].getAttribute('data-net-tab'));
  function resize(target, ctx){if(!target||!ctx)throw new Error('Canvas context is unavailable.');var box=target.getBoundingClientRect();if(!(box.width>0&&box.height>0))return null;var dpr=Math.min(window.devicePixelRatio||1,2);target.width=Math.max(1,Math.round(box.width*dpr));target.height=Math.max(1,Math.round(box.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);return {w:box.width,h:box.height};}
  function layerIndex(name){if(!data)return 0;var index=data.layers.indexOf(name);return index<0?0:index;}
  function layerZ(name){if(!data)return 0;var index=layerIndex(name);return (data.layers.length-1-index)*0.42;}
  // One coordinate policy for every report primitive and field: source board
  // coordinates retain their CAD top-left origin in 2D; 3D converts that same
  // point once to a right-handed world (+Y up).  Do not add per-layer flips.
  function project(point,z,size){var b=data.bounds,cx=(b.minX+b.maxX)/2,cy=(b.minY+b.maxY)/2;var dx=point[0]-cx,dy=point[1]-cy;var base=Math.min((size.w-52)/(b.maxX-b.minX||1),(size.h-52)/(b.maxY-b.minY||1))*zoom;if(view==='2d')return [size.w/2+panX+dx*base,size.h/2+panY+dy*base,0];var worldY=-dy,ca=Math.cos(yaw),sa=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);var rx=dx*ca-worldY*sa,ry=dx*sa+worldY*ca;return [size.w/2+panX+rx*base,size.h/2+panY-(ry*cp+z*sp)*base,(ry*sp-z*cp)];}
  function colorFor(value,min,max){var ratio=max===min?0.5:Math.max(0,Math.min(1,(value-min)/(max-min)));var position=ratio*(colors.length-1),left=Math.floor(position),right=Math.min(colors.length-1,left+1),mix=position-left;function rgb(hex){return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];}var a=rgb(colors[left]),b=rgb(colors[right]);return 'rgb('+Math.round(a[0]+(b[0]-a[0])*mix)+','+Math.round(a[1]+(b[1]-a[1])*mix)+','+Math.round(a[2]+(b[2]-a[2])*mix)+')';}
  function drawContour(samples,metric,min,max,size){contourHoverPoints=[];var triangles=[],budget=12000;for(var sampleIndex=0;sampleIndex<samples.length&&triangles.length<budget;sampleIndex++){var sample=samples[sampleIndex],vertices=sample.vertices_mm||[];if(vertices.length<3)continue;var values=sample.vertex_values||[];for(var vertexIndex=1;vertexIndex<vertices.length-1&&triangles.length<budget;vertexIndex++){var source=[vertices[0],vertices[vertexIndex],vertices[vertexIndex+1]],cornerValues=[values[0],values[vertexIndex],values[vertexIndex+1]].map(function(value){return Number.isFinite(value)?value:sample.value;}),center=[(source[0][0]+source[1][0]+source[2][0])/3,(source[0][1]+source[1][1]+source[2][1])/3],centerValue=(cornerValues[0]+cornerValues[1]+cornerValues[2])/3,layer=sample.layer||'F.Cu',z=layerZ(layer)+.65,projected=source.map(function(vertex){return project([vertex[0],vertex[1]],z,size);}),projectedCenter=project(center,z,size);for(var corner=0;corner<3&&triangles.length<budget;corner++){var next=(corner+1)%3,value=(cornerValues[corner]+cornerValues[next]+centerValue)/3;triangles.push({points:[projected[corner],projected[next],projectedCenter],depth:(projected[corner][2]+projected[next][2]+projectedCenter[2])/3,color:colorFor(value,min,max),sample:sample});}}}triangles.sort(function(a,b){return b.depth-a.depth;}).forEach(function(triangle){context.beginPath();triangle.points.forEach(function(point,index){if(index===0)context.moveTo(point[0],point[1]);else context.lineTo(point[0],point[1]);});context.closePath();context.fillStyle=triangle.color;context.globalAlpha=.86;context.fill();context.globalAlpha=1;var cx=(triangle.points[0][0]+triangle.points[1][0]+triangle.points[2][0])/3,cy=(triangle.points[0][1]+triangle.points[1][1]+triangle.points[2][1])/3;contourHoverPoints.push({x:cx,y:cy,value:triangle.sample.value,xMm:triangle.sample.x_mm,yMm:triangle.sample.y_mm,layer:triangle.sample.layer,net:triangle.sample.net,sourceId:triangle.sample.source_id||triangle.sample.element_id||''});});if(!triangles.length){context.fillStyle='#a7bbc4';context.font='13px sans-serif';context.fillText('No explicit solver faces are available for this field.',24,42);}}
  function polygon(points,z,size,fill,stroke){if(!points||points.length<2)return;context.beginPath();points.forEach(function(point,index){var p=project(point,z,size);if(index===0)context.moveTo(p[0],p[1]);else context.lineTo(p[0],p[1]);});context.closePath();if(fill){context.fillStyle=fill;context.fill();}if(stroke){context.strokeStyle=stroke;context.lineWidth=1;context.stroke();}}
  function rectanglePoints(center,width,height,degrees){var radians=(degrees||0)*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians);return [[-width/2,-height/2],[width/2,-height/2],[width/2,height/2],[-width/2,height/2]].map(function(offset){return [center[0]+offset[0]*c-offset[1]*s,center[1]+offset[0]*s+offset[1]*c];});}
  function drawBoard(){if(!canvas||!context){reportRuntimeIssue('Board canvas',new Error('2D canvas is unavailable in this report viewer.'));return;}var size=resize(canvas,context);if(!size)return;context.clearRect(0,0,size.w,size.h);context.fillStyle='#101a20';context.fillRect(0,0,size.w,size.h);if(!data){context.fillStyle='#a7bbc4';context.font='14px sans-serif';context.fillText('No imported board geometry is available.',24,40);markRenderReady(canvas,'.visual-shell');return;}
    var metric=metricSelect.value, samples=(data.fields&&data.fields[metric])||[];var range=samples.reduce(function(state,item){if(!Number.isFinite(item.value))return state;state.min=Math.min(state.min,item.value);state.max=Math.max(state.max,item.value);state.count++;return state;},{min:Infinity,max:-Infinity,count:0}),min=range.count?range.min:0,max=range.count?range.max:1;
    var copper='#c58a35',boardFill=view==='3d'?'rgba(43,98,74,.82)':'rgba(43,98,74,.62)';
    data.outlineLoops.forEach(function(loop){polygon(loop,0,size,boardFill,'#7f9da5');});
    data.zones.slice().sort(function(a,b){return layerIndex(b.l)-layerIndex(a.l);}).forEach(function(zone){polygon(zone.p,layerZ(zone.l),size,'rgba(183,126,47,.18)',null);});
    data.tracks.forEach(function(track){var a=project(track.s,layerZ(track.l),size),b=project(track.e,layerZ(track.l),size);context.beginPath();context.moveTo(a[0],a[1]);context.lineTo(b[0],b[1]);context.strokeStyle=copper;context.lineWidth=Math.max(1,track.w*Math.min(size.w/(data.bounds.maxX-data.bounds.minX||1),size.h/(data.bounds.maxY-data.bounds.minY||1))*zoom);context.lineCap='round';context.stroke();});
    data.pads.forEach(function(pad){polygon(rectanglePoints(pad.p,Math.max(.06,pad.w),Math.max(.06,pad.h),pad.r),layerZ(pad.l),size,'#d7a34b',null);});
    data.vias.forEach(function(via){var p=project(via.p,layerZ(via.ls&&via.ls[0]),size);var factor=Math.min(size.w/(data.bounds.maxX-data.bounds.minX||1),size.h/(data.bounds.maxY-data.bounds.minY||1))*zoom;context.beginPath();context.arc(p[0],p[1],Math.max(1.5,via.d*factor/2),0,Math.PI*2);context.fillStyle='#d7a34b';context.fill();context.beginPath();context.arc(p[0],p[1],Math.max(0.7,via.drill*factor/2),0,Math.PI*2);context.fillStyle='#101a20';context.fill();});
    data.components.forEach(function(component){polygon(rectanglePoints(component.p,Math.max(.08,component.w),Math.max(.08,component.h),component.r),view==='3d'?layerZ(component.l)+1.25:layerZ(component.l),size,null,'rgba(218,231,235,.55)');});
    contourHoverPoints=[];if(samples.length&&fieldDisplay!=='raw'){drawContour(samples,metric,min,max,size);}else if(samples.length){samples.forEach(function(sample){var p=project([sample.x_mm,sample.y_mm],sample.z_mm==null?layerZ(sample.layer):sample.z_mm,size),color=colorFor(sample.value,min,max),smooth=fieldDisplay==='smooth',radius=smooth?(view==='3d'?8:10):(view==='3d'?2.3:2.7);context.beginPath();context.arc(p[0],p[1],radius,0,Math.PI*2);if(smooth){var gradient=context.createRadialGradient(p[0],p[1],0,p[0],p[1],radius);gradient.addColorStop(0,color);gradient.addColorStop(.58,color);gradient.addColorStop(1,'rgba(0,0,0,0)');context.fillStyle=gradient;context.globalAlpha=.62;}else{context.fillStyle=color;context.globalAlpha=.9;}context.fill();context.globalAlpha=1;});}
    var bar=document.getElementById('viewport-colorbar');bar.hidden=!samples.length;document.getElementById('color-min').textContent=samples.length?min.toPrecision(4):'-';document.getElementById('color-max').textContent=samples.length?max.toPrecision(4):'-';document.getElementById('color-unit').textContent=metricSelect.options[metricSelect.selectedIndex].getAttribute('data-unit')||'';markRenderReady(canvas,'.visual-shell');
  }
  function resetView(){zoom=1;panX=0;panY=0;yaw=-0.65;pitch=0.72;drawBoard();}
  document.querySelectorAll('[data-board-view]').forEach(function(button){button.addEventListener('click',function(){view=button.getAttribute('data-board-view');document.querySelectorAll('[data-board-view]').forEach(function(item){item.classList.toggle('active',item===button);});document.getElementById('interaction-hint').textContent=view==='3d'?'Left drag orbit | Middle/right drag pan | Wheel zoom':'Drag pan | Wheel zoom | Double-click fit';resetView();});});
  metricSelect.addEventListener('change',drawBoard);document.querySelectorAll('[data-field-display]').forEach(function(button){button.addEventListener('click',function(){fieldDisplay=button.getAttribute('data-field-display');if(fieldDisplay==='contour'&&view!=='3d'){view='3d';document.querySelectorAll('[data-board-view]').forEach(function(item){item.classList.toggle('active',item.getAttribute('data-board-view')==='3d');});}document.querySelectorAll('[data-field-display]').forEach(function(item){item.classList.toggle('active',item===button);});drawBoard();});});canvas.addEventListener('contextmenu',function(event){event.preventDefault();});canvas.addEventListener('pointerdown',function(event){dragging=true;lastX=event.clientX;lastY=event.clientY;canvas.setPointerCapture(event.pointerId);});canvas.addEventListener('pointerup',function(){dragging=false;});canvas.addEventListener('pointermove',function(event){var viewportTooltip=document.getElementById('viewport-tooltip');if(!dragging){if(fieldDisplay!=='raw'&&contourHoverPoints.length){var box=canvas.getBoundingClientRect(),x=event.clientX-box.left,y=event.clientY-box.top,nearest=contourHoverPoints.reduce(function(best,point){var distance=(point.x-x)*(point.x-x)+(point.y-y)*(point.y-y);return !best||distance<best.distance?{point:point,distance:distance}:best;},null);if(nearest&&nearest.distance<625){var option=metricSelect.options[metricSelect.selectedIndex],unit=option.getAttribute('data-unit')||'';viewportTooltip.hidden=false;viewportTooltip.style.left=Math.min(box.width-220,x+14)+'px';viewportTooltip.style.top=Math.max(8,y-62)+'px';viewportTooltip.textContent=Number(nearest.point.value).toPrecision(7)+' '+unit+' | '+nearest.point.xMm.toFixed(3)+', '+nearest.point.yMm.toFixed(3)+' mm | '+nearest.point.layer+' | returned solver sample';return;}}viewportTooltip.hidden=true;return;}viewportTooltip.hidden=true;var dx=event.clientX-lastX,dy=event.clientY-lastY;lastX=event.clientX;lastY=event.clientY;if(view==='3d'&&event.buttons===1&&!event.shiftKey){yaw+=dx*.009;pitch=Math.max(.12,Math.min(1.45,pitch+dy*.009));}else{panX+=dx;panY+=dy;}scheduleBoardDraw();});canvas.addEventListener('pointerleave',function(){document.getElementById('viewport-tooltip').hidden=true;});canvas.addEventListener('wheel',function(event){event.preventDefault();zoom=Math.max(.18,Math.min(12,zoom*Math.exp(-event.deltaY*.001)));scheduleBoardDraw();},{passive:false});canvas.addEventListener('dblclick',resetView);
  function graphSeries(){if(!data)return null;var key=graphSelect.value;if(key.indexOf('impedance:')===0){var net=key.slice(10),network=data.impedance.find(function(item){return item.net===net;});return network?{label:'Impedance | '+net,unit:'ohm',xLabel:'Frequency (Hz)',logX:true,points:network.points.map(function(point){return [point.frequency_hz,point.magnitude_ohm,point];})}:null;}if(key.indexOf('transient:')===0){var field=key.slice(10),option=graphSelect.options[graphSelect.selectedIndex],frames=(data.timeSeries||[]).filter(function(frame){return frame.fields&&frame.fields[field];});return frames.length?{label:option.textContent,unit:option.getAttribute('data-unit')||'',xLabel:'Time (s)',logX:false,points:frames.map(function(frame){return [frame.time_s,frame.fields[field].maximum,{time_s:frame.time_s}];})}:null;}var samples=(data.fields&&data.fields[key])||[];var option=graphSelect.options[graphSelect.selectedIndex];return samples.length?{label:option.textContent,unit:option.getAttribute('data-unit')||'',xLabel:'Spatial sample',logX:false,points:samples.map(function(sample,index){return [index+1,sample.value,sample];})}:null;}
  var graphPlot=null, graphView=null;
  function drawGraph(){if(!graph||!graphContext){reportRuntimeIssue('Result graph',new Error('2D canvas is unavailable in this report viewer.'));return;}var size=resize(graph,graphContext);if(!size)return;graphContext.clearRect(0,0,size.w,size.h);graphContext.fillStyle='#fff';graphContext.fillRect(0,0,size.w,size.h);var series=graphSeries();if(!series||!series.points.length){graphContext.fillStyle='#657982';graphContext.font='13px sans-serif';graphContext.fillText('No graphable solver output is available.',24,42);graphPlot=null;markRenderReady(graph,'.graph-shell');return;}var points=series.points.filter(function(point){return Number.isFinite(point[0])&&Number.isFinite(point[1]);});var bounds=points.reduce(function(state,point){var x=series.logX?Math.log10(Math.max(point[0],1e-30)):point[0],y=point[1];state.minX=Math.min(state.minX,x);state.maxX=Math.max(state.maxX,x);state.minY=Math.min(state.minY,y);state.maxY=Math.max(state.maxY,y);return state;},{minX:Infinity,maxX:-Infinity,minY:Infinity,maxY:-Infinity}),minX=bounds.minX,maxX=bounds.maxX,minY=bounds.minY,maxY=bounds.maxY;if(maxY===minY){maxY+=1;minY-=1;}if(maxX===minX){maxX+=.5;minX-=.5;}if(graphView){minX=graphView.minX;maxX=graphView.maxX;minY=graphView.minY;maxY=graphView.maxY;}var left=62,right=18,top=24,bottom=44;function sx(value){var transformed=series.logX?Math.log10(Math.max(value,1e-30)):value;return left+(transformed-minX)/(maxX-minX||1)*(size.w-left-right);}function sy(value){return top+(maxY-value)/(maxY-minY)*(size.h-top-bottom);}graphContext.strokeStyle='#d9e1e4';graphContext.lineWidth=1;graphContext.font='10px sans-serif';graphContext.fillStyle='#61727a';for(var i=0;i<=5;i++){var y=top+i*(size.h-top-bottom)/5;graphContext.beginPath();graphContext.moveTo(left,y);graphContext.lineTo(size.w-right,y);graphContext.stroke();var label=maxY-(maxY-minY)*i/5;graphContext.fillText(label.toPrecision(4),4,y+3);}for(var j=0;j<=5;j++){var tickX=left+j*(size.w-left-right)/5,tickValue=minX+(maxX-minX)*j/5;graphContext.fillText((series.logX?Math.pow(10,tickValue):tickValue).toPrecision(4),tickX-15,size.h-bottom+16);}graphContext.save();graphContext.beginPath();graphContext.rect(left,top,size.w-left-right,size.h-top-bottom);graphContext.clip();graphContext.strokeStyle='#237d94';graphContext.lineWidth=1.7;graphContext.beginPath();points.forEach(function(point,index){var x=sx(point[0]),y=sy(point[1]);if(index===0)graphContext.moveTo(x,y);else graphContext.lineTo(x,y);});graphContext.stroke();graphContext.restore();graphContext.fillStyle='#1c3d49';graphContext.font='600 11px sans-serif';graphContext.fillText(series.xLabel,left,size.h-12);graphContext.save();graphContext.translate(13,size.h/2);graphContext.rotate(-Math.PI/2);graphContext.fillText(series.unit,0,0);graphContext.restore();graphPlot={points:points,sx:sx,sy:sy,series:series,minX:minX,maxX:maxX,minY:minY,maxY:maxY,left:left,top:top,right:size.w-right,bottom:size.h-bottom};markRenderReady(graph,'.graph-shell');}
  graph.addEventListener('pointermove',function(event){if(!graphPlot)return;var box=graph.getBoundingClientRect(),x=event.clientX-box.left;var nearest=graphPlot.points.reduce(function(best,point){var distance=Math.abs(graphPlot.sx(point[0])-x);return !best||distance<best.distance?{point:point,distance:distance}:best;},null);if(!nearest)return;var point=nearest.point,meta=point[2]||{};tooltip.hidden=false;tooltip.style.left=Math.min(box.width-205,Math.max(8,graphPlot.sx(point[0])+10))+'px';tooltip.style.top=Math.max(8,graphPlot.sy(point[1])-55)+'px';tooltip.textContent='';var title=document.createElement('b'),value=document.createElement('span'),detail=document.createElement('small');title.textContent=graphPlot.series.label;value.textContent=Number(point[1]).toPrecision(7)+' '+graphPlot.series.unit;detail.textContent=graphPlot.series.logX?Number(point[0]).toPrecision(6)+' Hz':meta.time_s!=null?'t '+Number(meta.time_s).toPrecision(7)+' s':((meta.x_mm==null?'Sample '+point[0]:'x '+Number(meta.x_mm).toFixed(3)+' mm | y '+Number(meta.y_mm).toFixed(3)+' mm')+(meta.layer?' | '+meta.layer:''));tooltip.append(title,value,detail);});graph.addEventListener('pointerleave',function(){tooltip.hidden=true;});graphSelect.addEventListener('change',function(){graphView=null;drawGraph();});
  graph.setAttribute('tabindex','0');graph.setAttribute('aria-label','Result graph. Wheel zooms; wheel over horizontal or vertical axis zooms only that axis. Double-click or press 0 to fit.');graph.setAttribute('title','Wheel: zoom | Axis hover: one axis | Double-click: fit');
  graph.addEventListener('wheel',function(event){if(!graphPlot)return;var box=graph.getBoundingClientRect(),x=event.clientX-box.left,y=event.clientY-box.top,p=graphPlot,inX=x>=p.left&&x<=p.right,inY=y>=p.top&&y<=p.bottom,zoomX=inX&&(inY||y>p.bottom),zoomY=inY&&(inX||x<p.left);if(!zoomX&&!zoomY)return;event.preventDefault();event.stopPropagation();var delta=event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?240:1),factor=Math.exp(Math.max(-.7,Math.min(.7,delta*.0015)));function range(a,b,f){var anchor=a+(b-a)*Math.max(0,Math.min(1,f));return [anchor+(a-anchor)*factor,anchor+(b-anchor)*factor];}var xr=zoomX?range(p.minX,p.maxX,(x-p.left)/(p.right-p.left)):[p.minX,p.maxX],yr=zoomY?range(p.minY,p.maxY,1-(y-p.top)/(p.bottom-p.top)):[p.minY,p.maxY];if(xr.concat(yr).every(Number.isFinite)&&xr[0]!==xr[1]&&yr[0]!==yr[1]){graphView={minX:xr[0],maxX:xr[1],minY:yr[0],maxY:yr[1]};drawGraph();}},{passive:false});
  function fitGraph(){graphView=null;drawGraph();}graph.addEventListener('dblclick',fitGraph);graph.addEventListener('keydown',function(event){if(event.key==='0'){event.preventDefault();fitGraph();}});
  var printButton=document.getElementById('print-report'),evidenceButton=document.getElementById('download-evidence');if(printButton)printButton.addEventListener('click',function(){window.print();});if(evidenceButton)evidenceButton.addEventListener('click',function(){var blob=new Blob([JSON.stringify(evidence,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=evidence.report_id+'-evidence.json';link.click();setTimeout(function(){URL.revokeObjectURL(link.href);},1000);});
  function redrawReportCanvases(){renderSafely('Board canvas',drawBoard);renderSafely('Result graph',drawGraph);}
  var resizeFrame=0;function scheduleReportRedraw(){if(resizeFrame)return;var redraw=function(){resizeFrame=0;redrawReportCanvases();};resizeFrame=window.requestAnimationFrame?window.requestAnimationFrame(redraw):setTimeout(redraw,32);}
  window.addEventListener('resize',scheduleReportRedraw);
  if(window.ResizeObserver){var canvasResizeObserver=new ResizeObserver(scheduleReportRedraw);if(canvas)canvasResizeObserver.observe(canvas);if(graph)canvasResizeObserver.observe(graph);}
  if(window.IntersectionObserver){var canvasVisibilityObserver=new IntersectionObserver(function(entries){if(entries.some(function(entry){return entry.isIntersecting;}))scheduleReportRedraw();},{root:null,rootMargin:'160px 0px',threshold:0});if(canvas)canvasVisibilityObserver.observe(canvas);if(graph)canvasVisibilityObserver.observe(graph);var sectionObserver=new IntersectionObserver(function(entries){var visible=entries.filter(function(entry){return entry.isIntersecting;}).sort(function(left,right){return Math.abs(left.boundingClientRect.top)-Math.abs(right.boundingClientRect.top);})[0];if(visible){var link=linkForHash('#'+visible.target.id);if(link)markCurrentNav(link);}},{root:null,rootMargin:'-10% 0px -70% 0px',threshold:0});navLinks.forEach(function(link){var target=targetForHash(navHash(link));if(target)sectionObserver.observe(target);});}
  window.addEventListener('beforeprint',redrawReportCanvases);window.addEventListener('afterprint',scheduleReportRedraw);
  redrawReportCanvases();
  }catch(error){reportRuntimeIssue('Report initialization',error);}
})();`;
