// SPDX-License-Identifier: Apache-2.0
import { openEMSFields, newOpenEMSPort, type OpenEMSSetup, type OpenEMSPort, type OpenEMSNumericKey } from "./openEMSSetup";
import "./OpenEMSExtension.css";
export { defaultOpenEMSSetup, openEMSParameters } from "./openEMSSetup";
export type { OpenEMSSetup, OpenEMSDomain } from "./openEMSSetup";
export function OpenEMSSetupForm({ value, onChange, netOptions, disabled = false }: { value: OpenEMSSetup; onChange: (value: OpenEMSSetup) => void; netOptions: string[]; disabled?: boolean }) {
  const patch = (update: Partial<OpenEMSSetup>) => onChange({ ...value, ...update });
  const portPatch = (index: number, update: Partial<OpenEMSPort>) => patch({ ports: value.ports.map((port, i) => i === index ? { ...port, ...update } : port) });
  const scalar = (key: OpenEMSNumericKey) => <label key={key}>{openEMSFields[key][0]}<input type="number" step={openEMSFields[key].length === 5 ? 1 : "any"} min={openEMSFields[key][2]} max={openEMSFields[key][3]} value={value[key]} onChange={event => patch({ [key]: event.target.value })} /></label>;
  const farScalar = (key: "radius_m" | "theta_start_deg" | "theta_stop_deg" | "theta_points" | "phi_start_deg" | "phi_stop_deg" | "phi_points" | "max_far_field_samples", label: string) => <label key={key}>{label}<input type="number" step={key.endsWith("points") || key.endsWith("samples") ? 1 : "any"} value={value[key]} onChange={event => patch({ [key]: event.target.value })} /></label>;
  return <fieldset className="openems-setup" disabled={disabled}>
    <legend>OpenEMS full-wave GUI setup</legend>
    <p>Explicit selected copper nets, physical stackup and lumped ports form this case. Gaussian excitation is generated from the sweep. High-frequency PI is a port sweep. Runtime, geometry and physical/resource admission remain worker checks; adapter results are approximate or unvalidated.</p>
    <label>Complete nets to export<select multiple aria-label="OpenEMS exported nets" value={value.net_names} onChange={event => patch({ net_names: Array.from(event.target.selectedOptions, option => option.value) })}>{[...new Set([...netOptions, ...value.net_names])].sort().map(net => <option key={net} value={net}>{net}</option>)}</select></label>
    <small>Select all signal and return conductors needed by the ports. Port endpoints must land on different exported nets; the worker checks this against actual geometry.</small>
    <div className="openems-fields">{(["frequency_start_hz", "frequency_stop_hz", "frequency_points", "mesh_resolution_mm", "dielectric_cells_per_layer", "air_padding_mm", "reference_impedance_ohm"] as OpenEMSNumericKey[]).map(scalar)}</div>
    <details><summary>Mesh and runtime limits</summary><p>These are editable setup values. Resource limits bound a run; they do not prove mesh convergence.</p><div className="openems-fields">{(["mesh_growth_ratio", "max_solver_time_s", "max_timesteps", "threads", "max_estimated_cells", "memory_limit_gib", "end_criteria", "via_plating_thickness_mm"] as OpenEMSNumericKey[]).map(scalar)}</div></details>
    <details><summary>Six boundary faces</summary><div className="openems-fields">{["X minimum", "X maximum", "Y minimum", "Y maximum", "Z minimum", "Z maximum"].map((label, index) => <label key={label}>{label}<input aria-label={`OpenEMS ${label} boundary`} list="openems-boundaries" value={value.boundary_conditions[index]} onChange={event => patch({ boundary_conditions: value.boundary_conditions.map((boundary, i) => i === index ? event.target.value : boundary) })} /></label>)}</div><datalist id="openems-boundaries">{["PML_8", "MUR", "PEC", "PMC"].map(boundary => <option key={boundary} value={boundary} />)}</datalist><small>Accepted: PEC, PMC, MUR, PML_1 through PML_99. NF2FF requires MUR or PML on every face.</small></details>
    <section className="openems-ports"><h4>Explicit lumped ports ({value.ports.length}/8)</h4><p>Geometry preparation can omit ports. Solver execution needs at least one port and exactly one excited port. Coordinates are millimetres in the exported board frame, with the top stackup surface at Z = 0 and layers extending toward negative Z.</p>
      {value.ports.map((port, index) => <fieldset key={index}><legend>Port {index + 1}</legend><div className="openems-fields">{(["start", "stop"] as const).flatMap(end => [0, 1, 2].map(axis => <label key={`${end}-${axis}`}>{end} {"XYZ"[axis]} (mm)<input type="number" step="any" aria-label={`Port ${index + 1} ${end} ${"XYZ"[axis]}`} value={port[end][axis]} onChange={event => portPatch(index, { [end]: port[end].map((coordinate, i) => i === axis ? event.target.value : coordinate) as [string, string, string] })} /></label>))}
        <label>Direction<select value={port.direction} onChange={event => portPatch(index, { direction: event.target.value as OpenEMSPort["direction"] })}>{["x", "y", "z"].map(axis => <option key={axis} value={axis}>{axis}</option>)}</select></label>
        <label>Impedance (ohm)<input type="number" step="any" value={port.impedance_ohm} onChange={event => portPatch(index, { impedance_ohm: event.target.value })} /></label>
      </div><label className="openems-check"><input type="checkbox" checked={port.excite} onChange={event => patch({ ports: value.ports.map((row, i) => ({ ...row, excite: i === index && event.target.checked })) })} />Excite this port</label><button type="button" onClick={() => patch({ ports: value.ports.filter((_, i) => i !== index) })}>Remove port {index + 1}</button></fieldset>)}
      <button type="button" disabled={value.ports.length >= 8} onClick={() => patch({ ports: [...value.ports, newOpenEMSPort()] })}>Add explicit port</button>
    </section>
    <label className="openems-check"><input type="checkbox" checked={value.far_field_enabled} onChange={event => patch({ far_field_enabled: event.target.checked })} />Request NF2FF radiation patterns</label>
    {value.far_field_enabled && <section><p>Supply frequencies within the sweep and a phase center inside the recording volume. The worker checks geometry and recording bounds. Angular output is generated from actual NF2FF data after a completed solve.</p>
      <label>NF2FF frequencies (Hz, comma separated)<input value={value.far_field_frequencies_hz} onChange={event => patch({ far_field_frequencies_hz: event.target.value })} /></label>
      <div className="openems-fields">{[0, 1, 2].map(axis => <label key={axis}>Phase center {"XYZ"[axis]} (mm)<input type="number" step="any" value={value.center_mm[axis]} onChange={event => patch({ center_mm: value.center_mm.map((coordinate, i) => i === axis ? event.target.value : coordinate) as [string, string, string] })} /></label>)}
      {farScalar("radius_m", "Observation radius (m)")}{farScalar("theta_start_deg", "Theta start (deg)")}{farScalar("theta_stop_deg", "Theta stop (deg)")}{farScalar("theta_points", "Theta samples")}{farScalar("phi_start_deg", "Phi start (deg)")}{farScalar("phi_stop_deg", "Phi stop (deg)")}{farScalar("phi_points", "Phi samples")}{farScalar("max_far_field_samples", "NF2FF total sample budget")}</div>
    </section>}
  </fieldset>;
}
