import { useEffect, useMemo, useRef, useState } from "react";
import { cancelLocalWorker, cancelLocalWorkerCleanup, openNativeTextFile, runLocalWorker, saveNativeTextFile } from "./workerBridge";
import { EXPLICIT_MESH_REQUEST_CONTRACT, FOCUSED_PCB_MESH_REQUEST_CONTRACT, focusedMeshFeedback, focusedMeshInventory, isFocusedPcbMeshRequest, updateFocusedSizing, validateFocusedPcbMeshRequest, type FocusedPcbMeshRequest, type ManualFocusRegion } from "./focusedMesh";

type Props = { onClose: () => void; onStatus: (message: string) => void };
const DEFAULT_REQUEST = { contract: "spike/gmsh-occ-mesh/v1", solids: [{ id: "fixture-cube", material_id: "fixture-material", priority: 0, shape: { kind: "polygon_prism", outer_mm: [[0, 0], [4, 0], [4, 3], [0, 3]], holes_mm: [], z_min_mm: 0, z_max_mm: 1 } }], mesh: { min_size_mm: 0.1, max_size_mm: 1, max_cells: 10000, max_vertices: 10000 } };
const boundedInteger = (value: unknown, minimum: number, maximum: number) => Number.isInteger(value) && Number(value) >= minimum && Number(value) <= maximum;
const MAX_RESULT_JSON_BYTES = 64 * 1024 * 1024;
const boundedJson = (value: unknown) => { const text = JSON.stringify(value, null, 2); if (new TextEncoder().encode(text).byteLength > MAX_RESULT_JSON_BYTES) throw new Error("Tetrahedral mesh JSON exceeds the 64 MiB UI exchange limit."); return text; };

export function parseTetraMeshRequest(text: string): Record<string, any> {
  if (text.length > 2_000_000) throw new Error("Tetrahedral mesh request exceeds the 2 MB editor limit.");
  const value = JSON.parse(text);
  if (isFocusedPcbMeshRequest(value)) return validateFocusedPcbMeshRequest(value);
  if (!value || typeof value !== "object" || Array.isArray(value) || value.contract !== EXPLICIT_MESH_REQUEST_CONTRACT || !Array.isArray(value.solids) || value.solids.length < 1 || value.solids.length > 64) throw new Error(`Expected a ${FOCUSED_PCB_MESH_REQUEST_CONTRACT} request or ${EXPLICIT_MESH_REQUEST_CONTRACT} request with 1–64 explicit solids.`);
  const mesh = value.mesh;
  if (!mesh || typeof mesh !== "object" || !Number.isFinite(mesh.min_size_mm) || !Number.isFinite(mesh.max_size_mm) || mesh.min_size_mm < 0.000001 || mesh.max_size_mm < mesh.min_size_mm || !boundedInteger(mesh.max_cells, 4, 100000) || !boundedInteger(mesh.max_vertices, 4, 100000)) throw new Error("Mesh sizes or output budgets are invalid.");
  return value;
}

export function normalizeTetraMeshResult(value: any): Record<string, any> {
  if (!value || typeof value !== "object" || Array.isArray(value) || !["spike/gmsh-occ-mesh-result/v1", "spike/gmsh-occ-mesh-result/v2"].includes(value.contract)) throw new Error("Expected a spike/gmsh-occ-mesh-result/v1 or v2 result.");
  const mesh = value.mesh; const counts = mesh?.counts;
  if (!mesh || mesh.contract !== "spike/solver-mesh/v1" || !Array.isArray(mesh.vertices) || !Array.isArray(mesh.cells) || !counts || counts.vertices !== mesh.vertices.length || counts.cells !== mesh.cells.length || !boundedInteger(counts.vertices, 4, 100000) || !boundedInteger(counts.cells, 4, 100000)) throw new Error("Tetrahedral result mesh counts or bounded arrays are invalid.");
  return value;
}

export default function TetraMeshPanel({ onClose, onStatus }: Props) {
  const [text, setText] = useState(() => JSON.stringify(DEFAULT_REQUEST, null, 2));
  const [prepared, setPrepared] = useState<Record<string, any> | null>(null);
  const [result, setResult] = useState<Record<string, any> | null>(null);
  const [resultSource, setResultSource] = useState<"worker" | "import" | null>(null);
  const [intendedUse, setIntendedUse] = useState<"SI" | "EM" | "Thermal">("EM");
  const [error, setError] = useState(""); const [busyStage, setBusyStage] = useState<"prepare" | "generate" | null>(null); const requestId = useRef<string | null>(null);
  const busy = busyStage !== null;
  const focusedRequest = useMemo(() => { try { const value = JSON.parse(text); return isFocusedPcbMeshRequest(value) ? value as FocusedPcbMeshRequest : null; } catch { return null; } }, [text]);
  const inventory = useMemo(() => focusedRequest ? focusedMeshInventory(focusedRequest) : null, [focusedRequest]);
  useEffect(() => () => { if (requestId.current) void cancelLocalWorkerCleanup(requestId.current); }, []);
  const replaceRequest = (request: Record<string, any>) => { setText(JSON.stringify(request, null, 2)); setPrepared(null); setResult(null); setResultSource(null); setError(""); };
  const editFocused = (patch: Partial<FocusedPcbMeshRequest["sizing"]>) => { if (!focusedRequest) return; replaceRequest(updateFocusedSizing(focusedRequest, patch)); };
  const importJson = async () => {
    try { const file = await openNativeTextFile("result"); if (!file) return; if (new TextEncoder().encode(file.contents).byteLength > MAX_RESULT_JSON_BYTES) throw new Error("Tetrahedral mesh JSON exceeds the 64 MiB UI exchange limit."); const parsed = JSON.parse(file.contents);
      if (["spike/gmsh-occ-mesh-result/v1", "spike/gmsh-occ-mesh-result/v2"].includes(parsed?.contract)) { setResult(normalizeTetraMeshResult(parsed)); setResultSource("import"); setError(""); onStatus(`Loaded tetrahedral mesh result ${file.fileName}; qualification claims remain untrusted imported metadata.`); }
      else { const request = parseTetraMeshRequest(file.contents); replaceRequest(request); onStatus(`Loaded ${isFocusedPcbMeshRequest(request) ? "whole-board focused" : "explicit"} tetrahedral mesh request ${file.fileName}.`); }
    } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); }
  };
  const prepare = async () => {
    try { const request = structuredClone(validateFocusedPcbMeshRequest(JSON.parse(text))); setBusyStage("prepare"); setError(""); setPrepared(null); setResult(null); const id = globalThis.crypto?.randomUUID?.() ?? `pcb-mesh-prepare-${Date.now()}`; requestId.current = id;
      const response = await runLocalWorker({ id, method: "prepare_pcb_volume_mesh", params: { request } });
      if (requestId.current !== id) return; if (!response.ok || !response.result) throw new Error(response.error ?? "Whole-board mesh preparation returned no result.");
      setPrepared(response.result); onStatus("Prepared the complete PCB volume and focused size field. Review the retained geometry evidence before generation.");
    } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); }
    finally { requestId.current = null; setBusyStage(null); }
  };
  const run = async () => {
    try { const parsed = structuredClone(parseTetraMeshRequest(text)); const request = isFocusedPcbMeshRequest(parsed) ? prepared?.job : parsed; if (!request) throw new Error("Prepare the focused whole-board request before generating its mesh."); setBusyStage("generate"); setError(""); setResult(null); const id = globalThis.crypto?.randomUUID?.() ?? `tetra-mesh-${Date.now()}`; requestId.current = id;
      const response = await runLocalWorker({ id, method: "generate_tetrahedral_mesh", params: { request, timeout_s: 180, memory_limit_mb: 2048 } });
      if (requestId.current !== id) return; if (!response.ok || !response.result) throw new Error(response.error ?? "Tetrahedral mesher returned no result.");
      setResult(normalizeTetraMeshResult(response.result)); setResultSource("worker"); onStatus(`Generated a tetrahedral mesh intended for ${intendedUse} review. It remains an exported mesh until a compatible solver admits it.`);
    } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); }
    finally { requestId.current = null; setBusyStage(null); }
  };
  const toggle = (values: string[], value: string) => values.includes(value) ? values.filter(item => item !== value) : [...values, value];
  const changeRegion = (index: number, update: (region: ManualFocusRegion) => ManualFocusRegion) => { if (!focusedRequest) return; editFocused({ regions: focusedRequest.sizing.regions.map((region, itemIndex) => itemIndex === index ? update(region) : region) }); };
  const counts = result?.mesh?.counts ?? {}; const metrics = result?.metrics ?? {}; const feedback = focusedMeshFeedback(result); const preparedEvidence = prepared?.focus_plan?.evidence;
  return <div className="modal-shade" role="presentation" onKeyDown={event => { if (event.key === "Escape" && !busy) onClose(); }}><section className="floating-panel tetra-mesh-panel" role="dialog" aria-modal="true" aria-labelledby="tetra-mesh-title">
    <div className="floating-heading"><div><b id="tetra-mesh-title">WHOLE-BOARD TETRAHEDRAL MESH</b><small>Focused sizing with complete PCB geometry retention</small></div><button autoFocus disabled={busy} onClick={onClose} aria-label="Close tetrahedral mesh tool">×</button></div>
    <p className="modal-note">Import a versioned normalized PCB volume request, choose where the mesh is fine, prepare the complete board volume, then generate first-order tetrahedra. Net and source selection changes element sizing; it does not crop unselected copper, dielectric, drills, or vias. This panel does not convert KiCad files.</p>
    <div className="field-row"><label>Intended mesh use<select aria-label="Intended mesh use" disabled={busy} value={intendedUse} onChange={event => setIntendedUse(event.target.value as typeof intendedUse)}><option>SI</option><option>EM</option><option>Thermal</option></select></label><p className="mcad-gate">This label records review intent. Generation does not attach the mesh to an SI, EM, or thermal solver.</p></div>
    {focusedRequest && inventory && <section aria-label="Focused whole-board sizing controls">
      <h3>Focus selection</h3>
      <div className="field-row"><fieldset><legend>Nets</legend>{inventory.nets.map(net => <label key={net}><input type="checkbox" disabled={busy} checked={focusedRequest.sizing.net_names.includes(net)} onChange={() => editFocused({ net_names: toggle(focusedRequest.sizing.net_names, net) })} /> {net}</label>)}</fieldset><fieldset><legend>Source traces and vias</legend><div style={{ maxHeight: 150, overflow: "auto" }}>{inventory.sources.map(source => <label key={source.id}><input type="checkbox" disabled={busy} checked={focusedRequest.sizing.source_ids.includes(source.id)} onChange={() => editFocused({ source_ids: toggle(focusedRequest.sizing.source_ids, source.id) })} /> {source.id} · {source.net} · {source.layer_id}</label>)}</div></fieldset></div>
      <div className="field-row">{([['Fine size', 'fine_size_mm'], ['Coarse background', 'coarse_size_mm'], ['Halo', 'halo_mm'], ['Growth rate', 'growth_rate']] as const).map(([label, key]) => <label key={key}>{label}<input aria-label={label} type="number" min={key === 'halo_mm' ? 0 : 0.000001} max={key === 'growth_rate' ? 1 : undefined} step="any" disabled={busy} value={focusedRequest.sizing[key]} onChange={event => editFocused({ [key]: Number(event.target.value) })} /></label>)}</div>
      <h3>Manual regions</h3>
      {focusedRequest.sizing.regions.map((region, index) => <div className="field-row" key={`${region.id}:${index}`}><label>Region ID<input aria-label={`Region ${index + 1} ID`} disabled={busy} value={region.id} onChange={event => changeRegion(index, current => ({ ...current, id: event.target.value }))} /></label>{region.bounds_mm.flatMap((point, pointIndex) => point.map((coordinate, axis) => <label key={`${pointIndex}:${axis}`}>{pointIndex ? 'Max' : 'Min'} {['X', 'Y', 'Z'][axis]}<input aria-label={`Region ${index + 1} ${pointIndex ? 'maximum' : 'minimum'} ${['X', 'Y', 'Z'][axis]}`} type="number" step="any" disabled={busy} value={coordinate} onChange={event => changeRegion(index, current => { const bounds = current.bounds_mm.map(item => [...item]) as ManualFocusRegion['bounds_mm']; bounds[pointIndex][axis] = Number(event.target.value); return { ...current, bounds_mm: bounds }; })} /></label>))}<label>Target size<input aria-label={`Region ${index + 1} target size`} type="number" min="0.000001" step="any" disabled={busy} value={region.target_size_mm} onChange={event => changeRegion(index, current => ({ ...current, target_size_mm: Number(event.target.value) }))} /></label><button className="secondary-btn" disabled={busy} onClick={() => editFocused({ regions: focusedRequest.sizing.regions.filter((_, itemIndex) => itemIndex !== index) })}>Remove</button></div>)}
      <button className="secondary-btn" disabled={busy} onClick={() => editFocused({ regions: [...focusedRequest.sizing.regions, { id: `region-${focusedRequest.sizing.regions.length + 1}`, bounds_mm: [[0, 0, 0], [1, 1, 1]], target_size_mm: focusedRequest.sizing.fine_size_mm }] })}>Add manual region</button>
    </section>}
    <details open={!focusedRequest}><summary>Request JSON</summary><label>Versioned mesh request<textarea aria-label="Tetrahedral mesh request JSON" rows={focusedRequest ? 10 : 18} disabled={busy} value={text} onChange={event => { setText(event.target.value); setPrepared(null); setResult(null); setResultSource(null); }} /></label></details>
    <div className="field-row"><button className="secondary-btn" disabled={busy} onClick={() => replaceRequest(DEFAULT_REQUEST)}>Load explicit cube</button><button className="secondary-btn" disabled={busy} onClick={() => void importJson()}>Import request / result JSON</button><button className="secondary-btn" disabled={busy} onClick={() => { try { const request = parseTetraMeshRequest(text); void saveNativeTextFile(isFocusedPcbMeshRequest(request) ? "pcb-focused-mesh-request.json" : "tetra-mesh-request.json", boundedJson(request), "result").catch(caught => setError(caught instanceof Error ? caught.message : String(caught))); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } }}>Export normalized request</button>{result && <button className="secondary-btn" disabled={busy} onClick={() => { try { void saveNativeTextFile("tetra-mesh-result.json", boundedJson(result), "result").catch(caught => setError(caught instanceof Error ? caught.message : String(caught))); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } }}>Export result</button>}</div>
    {focusedRequest && <div className="field-row"><button className="secondary-btn" disabled={busy} onClick={() => void prepare()}>Prepare whole-board mesh</button><button className="run-btn" disabled={busy || !prepared} onClick={() => void run()}>Generate prepared mesh</button></div>}
    {!focusedRequest && <button className={busy ? "run-btn stop" : "run-btn"} onClick={() => void (busy && requestId.current ? cancelLocalWorker(requestId.current) : run())}>{busy ? "Stop tetrahedral mesh" : "Generate explicit mesh"}</button>}
    {focusedRequest && busy && <button className="run-btn stop" onClick={() => void (requestId.current && cancelLocalWorker(requestId.current))}>Stop {busyStage === "prepare" ? "preparation" : "generation"}</button>}
    {prepared && <section aria-label="Whole-board preparation evidence"><p><b>READY TO GENERATE</b> · {preparedEvidence?.retained_solid_count ?? "?"} solids retained · {preparedEvidence?.generated_box_count ?? "?"} focus boxes</p><dl><dt>Geometry cropped</dt><dd>{preparedEvidence?.geometry_cropped === false ? "No" : "Unreported"}</dd><dt>Metadata coverage</dt><dd>{preparedEvidence?.metadata_coverage_complete === true ? "Complete" : "Unreported"}</dd><dt>Selected sources</dt><dd>{Array.isArray(preparedEvidence?.selected_source_ids) ? preparedEvidence.selected_source_ids.join(", ") || "Manual regions only" : "Unavailable"}</dd><dt>Preparation qualification</dt><dd>{prepared.production_qualified === true ? "Worker reported yes" : "Not production qualified"}</dd></dl></section>}
    {error && <p role="alert">{error}</p>}{result && <section aria-label="Tetrahedral mesh result"><p><b>{String(result.status ?? "returned").toUpperCase()}</b> · {Number(counts.vertices ?? 0).toLocaleString()} vertices · {Number(counts.cells ?? 0).toLocaleString()} tetrahedra · {Array.isArray(result.interface_faces) ? result.interface_faces.length.toLocaleString() : "unavailable"} interfaces</p><dl><dt>Scope</dt><dd>{String(result.scope ?? "unreported")}</dd><dt>Production qualified</dt><dd>{resultSource === "import" ? "Unverified imported claim" : result.production_qualified === true ? "Worker reported yes" : "No"}</dd><dt>CAD volume</dt><dd>{typeof metrics.cad_volume_mm3 === "number" ? `${metrics.cad_volume_mm3.toPrecision(7)} mm³` : "Unavailable"}</dd><dt>Minimum mean-ratio quality</dt><dd>{feedback.minimumQuality === null ? "Unavailable" : feedback.minimumQuality.toPrecision(6)}</dd><dt>Volume coverage error</dt><dd>{feedback.volumeError === null ? "Unavailable" : `${(feedback.volumeError * 100).toPrecision(4)}%`}</dd><dt>Source volume coverage</dt><dd>{feedback.coveredSources === null || feedback.mappedSources === null ? "Unavailable" : `${feedback.coveredSources} of ${feedback.mappedSources} mapped sources`}</dd><dt>Whole model retained</dt><dd>{result.focus_assessment ? feedback.wholeModelRetained ? "Yes" : "No or unreported" : "Not applicable to explicit request"}</dd><dt>Focused / background cells</dt><dd>{feedback.nearFocusCells === null ? "Unavailable" : `${feedback.nearFocusCells} / ${feedback.farFieldCells}`}</dd><dt>Cells above requested target</dt><dd>{feedback.aboveTargetCells === null ? "Unavailable" : `${feedback.aboveTargetCells}; maximum edge/target ${feedback.maximumEdgeRatio?.toPrecision(5) ?? "unavailable"}`}</dd></dl><p className="mcad-gate">The mesh is retained for export and review. Solver use requires a separate compatible admission path.</p></section>}
  </section></div>;
}
